name: objectid_example
description: ObjectId example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  benchmark_harness: any
  uuid: any
  objectid:
    path: ../

dev_dependencies:
  pedantic: ^1.9.0
