name: objectid_example
description: ObjectId example.
version: 1.0.0
publish_to: none
executables: 
  example: ./bin/example.dart

environment:
  sdk: "^3.0.0"

dependencies:
  benchmark_harness: ^2.2.2
  uuid: ^4.5.0
  objectid:
    path: ../

dev_dependencies:
  lints: ^4.0.0

