name: objectid_example
description: ObjectId example.
version: 1.0.0
publish_to: none
executables: 
  example: ./bin/example.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  benchmark_harness: any
  uuid: any
  objectid:
    path: ../

dev_dependencies:
  lints: ^2.1.0

