name: objectid
description: Blazing fast, cross-platform ObjectId implementation for the dart language.
version: 3.0.0
homepage: https://github.com/gonuit/dart_objectid
repository: https://github.com/gonuit/dart_objectid

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  matcher: ^0.12.16
