name: objectid
description: Blazing fast, cross-platform ObjectId implementation for the dart language.
version: 0.1.0-dev.1
homepage: https://github.com/gonuit/dart_objectid
repository: https://github.com/gonuit/dart_objectid

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  matcher: ^0.12.9
